Fixes installation on PHP 8.1, Fixes CI errors, includes Vocalink 7.30 spec
cs278/bank-modulus pull request #157
Opened 2023-04-12 16:09 UTC by JeremySkinner

This PR resolves several issues:

- Ensures the module can be installed on PHP 8.1 by adding missing php versions to composer.json
- Updates deprecated github actions
- Resolves issues with incompatible versions of composer being installed depending on php version (php 5.x requires composer version < 2.3) 
- Adds allowed plugins section to composer.json to allow installation with composer 2.x
- Migrates phpunit config to modern schema

Also includes the changes from #122 (Updates to Vocalink 7.30)

2023-04-20 09:33 UTC, JeremySkinner commented
Updated to support the v7.40 spec

2023-04-20 20:25 UTC, Olympic1 requested changes

2023-04-20 20:29 UTC, JeremySkinner commented on tests/Spec/DefaultSpecFactoryTest.php
> +            ['VocaLinkV740', new \DateTime('2023-06-05')],
Added - thanks!

2023-09-19 11:27 UTC, cs278 commented on composer.json
> +        "php": "^5.6 || ^7.2 || ^8.0 || ^8.1 || ^8.2",
This change isn't needed `^8.0` covers all PHP 8 versions.

2023-09-19 11:28 UTC, cs278 commented on phpunit.xml.dist
> +<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" backupGlobals="false" backupStaticAttributes="false" colors="true" convertErrorsToExceptions="true" convertNoticesToExceptions="true" co
I'll do this update when dropping PHP 5 support.

2023-09-19 16:50 UTC, cs278 commented
I think I've pulled in everything else from this PR, thanks @JeremySkinner and @Olympic1

2023-09-19 16:50 UTC, closed without merging